[package]
name = "pencil-array"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "MPI-distributed pencil arrays and transposes"
readme = "README.md"
include = ["Cargo.toml", "Cargo.lock", "README.md", "LICENSE", "NOTICE.md", "src/**/*.rs", "tests/**/*.rs", "examples/**/*.rs"]

[dependencies]
mpi = { workspace = true, features = ["complex"] }
num-complex = "0.4.6"
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
